// react/src/page/player/comment/index.jsx
import React from 'react'
import PropTypes from 'prop-types'
import './index.css'
import like from '@/assets/like.svg'

/**
 * 歌曲热门评论组件
 */
function Comment({ data: { username, time, avatarUrl, likedCount, content } }) {
  return (
    <div className="comment_item">
      <div className="cmt_img">
        <img src={avatarUrl} alt="avatar" />
      </div>
      <div className="cmt_wrap">
        <div className="cmt_header">
          <div className="cmt_info">
            <span className="cmt_username">{username}</span>
            <span className="cmt_time">{time}</span>
          </div>
          <div className="cmt_like">
            <span>{likedCount}</span>
            <i>
              <img src={like} alt="点赞" />
            </i>
          </div>
        </div>
        <div className="cmt_content">
          <span>{content}</span>
        </div>
      </div>
    </div>
  )
}

Comment.propTypes = {
  data: PropTypes.object.isRequired,
}

export default Comment

// vue/src/components/comment.vue
<template>
  <div class="comment_item">
    <div class="cmt_img">
      <img v-lazy="data.avatarUrl" alt="头像" />
    </div>
    <div class="cmt_wrap">
      <div class="cmt_header">
        <div class="cmt_info">
          <span class="cmt_username">{{ data.username }}</span>
          <span class="cmt_time">{{ data.time }}</span>
        </div>
        <div class="cmt_like">
          <span>{{ data.likedCount }}</span>
          <i><img src="@/assets/like.svg" alt="点赞" /></i>
        </div>
      </div>
      <div class="cmt_content">
        <span>{{ data.content }}</span>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    data: {
      type: Object,
      required: true,
    },
  },
};
</script>

<style scoped>
@import url('~@/styles/comment.css');
</style>
