// next/components/home.jsx
import Footer from './footer'
import RemdList from './recommend'
import Song from './song'

/**
 * 首屏
 */
function Home({ remd, newSong }) {
  return (
    <div className="content">
      <h2 className="remd">推荐歌单</h2>
      <div className="list">
        {remd.slice(0, 3).map((value) => (
          <RemdList {...value} key={value.id} />
        ))}
      </div>
      <div className="list">
        {remd.slice(3, 6).map((value) => (
          <RemdList {...value} key={value.id} />
        ))}
      </div>
      <h2 className="remd">最新音乐</h2>
      <section>
        {newSong.map((value) => (
          <Song data={value} key={value.id} />
        ))}
      </section>
      <Footer />
      <style jsx>
        {`
          .content {
            background-color: #fff;
          }
          .remd {
            display: block;
            position: relative;
            padding-left: 9px;
            margin-bottom: 14px;
            font-size: 17px;
            font-weight: 400;
            height: 20px;
            line-height: 20px;
          }
          .remd:after {
            content: ' ';
            position: absolute;
            left: 0;
            top: 50%;
            margin-top: -9px;
            width: 2px;
            height: 16px;
            background-color: #d33a31;
          }
          .list:after {
            display: block;
            visibility: hidden;
            clear: both;
            height: 0;
            overflow: hidden;
            content: '.';
          }
        `}
      </style>
    </div>
  )
}

export default Home

// src/components/Tabs/Home.vue
<template>
    <div class="content">
        <h2 class="remd">推荐歌单</h2>
        <SongList></SongList>
        <h2 class="remd">最新音乐</h2>
        <div>
            <section v-if="error">
                <h1>加载失败</h1>
            </section>
            <section v-else>
                <div v-if="loading">loading</div>
                <Song v-else v-for="item in data" :key="item.id" :music="item"></Song>
            </section>
        </div>
        <foot></foot>
    </div>
</template>

<script>
    import SongList from '@/components/SongList.vue'
    import Song from '@/components/Song.vue'
    import foot from '@/components/Footer/foot.vue'
    import { mapActions } from 'vuex'
    export default {
        name: 'home',
        components: {
            SongList,
            Song,
            foot
        },
        data () {
            return{
                loading: true,
                data: [],
                error: false
            }
        },
        methods: {
            ...mapActions([
                'newSong'
            ])
        },
        created () {
            this.newSong().then(() => {
                this.loading = false;
                this.data = this.$store.getters.newSong;
            }).catch(() => {
                this.error = true;
            })
        }
    }
</script>

<style scoped>
    .content {
        height: 100%;
        padding-top: 20px;
    }
    .remd {
        display: block;
        position: relative;
        padding-left: 9px;
        margin-bottom: 14px;
        font-size: 17px;
        font-weight: 400;
        height: 20px;
        line-height: 20px;
    }
    .remd:after{
        content: " ";
        position: absolute;
        left: 0;
        top: 50%;
        margin-top: -9px;
        width: 2px;
        height: 16px;
        background-color: #d33a31;
    }
</style>
