// src/page/playList.vue
<template>
  <div class="playlistwrap">
    <section class="list-head">
      <div class="list-head-bg" :style="bgStyle"></div>
      <div class="getBack" @click="goBack">
        <h3>返回</h3>
      </div>
      <div class="list-head-content">
        <div class="lhc-img">
          <img v-lazy="listDetail.imgUrl" alt="pic" />
          <span class="s-icon">歌单</span>
        </div>
        <div class="lhc-info">
          <h2 class="lhc-title">{{ listDetail.name }}</h2>
        </div>
      </div>
    </section>
    <section class="list-info">
      <div class="info-tags">
        标签:
        <em class="tag" v-for="tag in listDetail.tags" :key="tag">{{ tag }}</em>
      </div>
      <div class="info-intro" v-if="listDetail.des">
        <span
          >简介：{{ listDetail.des.substring(0, 100) }}
          <span v-if="listDetail.des.length > 100">......</span></span
        >
      </div>
    </section>
    <div class="list-song">
      <h3>歌曲列表</h3>
      <Song
        v-for="item in listDetail.music"
        :key="item.id"
        :music="item"
      ></Song>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import Song from '@/components/song.vue';

export default {
  components: {
    Song,
  },
  computed: {
    ...mapGetters(['listDetail']),
    bgStyle() {
      return {
        backgroundImage: `url(${this.listDetail.imgUrl})`,
      };
    },
  },
  methods: {
    goBack() {
      this.$router.back();
    },
  },
};
</script>

<style scoped>
@import '~@/styles/playlist_page.css';
</style>

// react/src/page/playlist/index.jsx
import React from 'react'
import { LazyLoadImage } from 'react-lazy-load-image-component'
import Song from '@/components/song/'
import { connect } from 'react-redux'
import styles from './index.module.css'

/**
 * 歌单详情页面
 * @author janyin
 */
function PlayList({
  playList: { imgUrl, name, tags, desc, music },
  history: { goBack },
}) {
  return (
    <div className={styles.playlistwrap}>
      <section className={styles.list_head}>
        <div
          className={styles.list_head_bg}
          style={{ backgroundImage: `url(${imgUrl})` }}
        />
        <div className={styles.getBack} onClick={goBack}>
          <h3>返回</h3>
        </div>
        <div className={styles.list_head_content}>
          <div className={styles.lhc_img}>
            <LazyLoadImage src={imgUrl} alt="pic" />
            <span className={styles.s_icon}>歌单</span>
          </div>
          <div className={styles.lhc_info}>
            <h2 className={styles.lhc_title}>{name}</h2>
          </div>
        </div>
      </section>
      <section className={styles.list_info}>
        <div className={styles.info_tags}>
          标签:
          {tags &&
            tags.map((value) => (
              <em className={styles.tag} key={value}>
                {value}
              </em>
            ))}
        </div>
        {desc && (
          <div className={styles.info_intro}>
            <span>
              简介：
              {desc.substring(0, 100)}
            </span>
          </div>
        )}
      </section>
      <div className={styles.list_song}>
        <h3>歌曲列表</h3>
        {music && music.map((value) => <Song data={value} key={value.id} />)}
      </div>
    </div>
  )
}

export default connect((state) => ({
  playList: state.playList,
}))(PlayList)
